// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/narrative-impact/HorizontalScroll.tsx": () => import("../components/mockups/narrative-impact/HorizontalScroll.tsx"),
  "./components/mockups/narrative-impact/NumberGrid.tsx": () => import("../components/mockups/narrative-impact/NumberGrid.tsx"),
  "./components/mockups/narrative-impact/StackedAccordion.tsx": () => import("../components/mockups/narrative-impact/StackedAccordion.tsx")
};
